name: flutter_section_list_view
description: An extended flutter listview to support sections like iOS UITableView
version: 0.0.1
author: Dharmendra Singh Yadav <dsyadav.glaitm@gmail.com>
homepage: https://github.com/dharmendraiosdev/flutter_section_list_view

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter